"""in user add verification_code

Revision ID: 48edecefcf04
Revises: 
Create Date: 2023-10-02 21:14:05.926905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48edecefcf04'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.alter_column('created_date',
               existing_type=sa.DATETIME(),
               type_=sa.String(length=50),
               existing_nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verification_code', sa.String(length=8), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('verification_code')

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.alter_column('created_date',
               existing_type=sa.String(length=50),
               type_=sa.DATETIME(),
               existing_nullable=True)

    # ### end Alembic commands ###
